### ISSUE TITLE
java.io.FileNotFoundException: Could not create dir: /tmp/BackupRoot/@BackSnap/manjaro18/snapshots

### ISSUE THREAD

**Issue by JackDinn** [andreaskielkopf/BackSnap#5]
After first installing and running it did do a full backup of my btrfs system to an external drive (btrfs).

However, after that it would just error every time i try to run it.

```
❱sudo backsnap -gi
BackSnap Version 0.6.7.10 (2023/11/02)
args >  -gi 
java [version=22, major=22, minor=null, patch=null]
using ThreadPerTaskExecutor
Pc[sudo ] & Id:4ac04e63-d68d-47d1-a6c5-f33d9f7c29de
OneBackup[srcPc=Pc[sudo ], srcPath=/, backupLabel=manjaro18, flags=null]
OneBackup[srcPc=Pc[sudo ], srcPath=/home, backupLabel=manjaro18.home, flags=null]
sudo mkdir --mode=000 -p /tmp/BtrfsRoot;sudo mount -t btrfs -o subvol=/ /dev/nvme0n1p5 /tmp/BtrfsRoot
Backup snapshots from sudo :/
sudo mkdir --mode=000 -p /tmp/BackupRoot;sudo mount -t btrfs -o subvol=/,compress=zstd:9  /dev/sda3 /tmp/BackupRoot
Try to use backupDir  sudo :/tmp/BackupRoot
Snap: snapshots 2024-06-09_18-00-00 2024-06-10_16-10-54 2024-06-10_18-00-00 2024-06-11_18-00-00 2024-06-12_04-27-01
 2024-06-12_20-00-01 2024-06-13_20-00-01 2024-06-14_07-31-41 2024-06-14_07-32-06 2024-06-14_20-00-00 2024-06-15_11-00-00
 2024-06-15_20-00-00 2024-06-15_21-00-00

Skip: 2024-06-09_18-00-00 2024-06-10_16-10-54 2024-06-10_18-00-00 2024-06-11_18-00-00 2024-06-12_04-27-01
 2024-06-12_20-00-01 2024-06-13_20-00-01 2024-06-14_07-31-41 2024-06-14_07-32-06 2024-06-14_20-00-00 2024-06-15_11-00-00
manjaro18: Backup of snapshots based on 2024-06-15_11-00-00
java.io.FileNotFoundException: Could not create dir: /tmp/BackupRoot/@BackSnap/manjaro18/snapshots
        at de.uhingen.kielkopf.andreas.backsnap.Backsnap.mkDirs(Backsnap.java:309)
        at de.uhingen.kielkopf.andreas.backsnap.Backsnap.backup(Backsnap.java:249)
        at de.uhingen.kielkopf.andreas.backsnap.Backsnap.main(Backsnap.java:167)

Mount passt nicht für: Mount [sudo :/dev/nvme0n1p5 -> /home(/@home:0)] -> Snapshot[mount=Mount [sudo :/dev/nvme0n1p5 -> /(/@:14)], id=802, gen=20477, cgen=20475, parent=351, top_level=351, otime=null, parent_uuid=35dbf6d2-33cf-7d44-914e-39556b0a73ac, received_uuid=-, uuid=a02fd339-91dc-ec4c-b951-4ad4a933d409, btrfsPath=/@/mnt/snapshots/home-2024-06-15_14-30-00, readonlyL=readonly[null]]
Backup snapshots from sudo :/home
Try to use backupDir  sudo :/tmp/BackupRoot
Snap: snapshots 2024-06-09_18-00-00 2024-06-10_16-10-54 2024-06-10_18-00-00 2024-06-11_18-00-00 2024-06-12_04-27-01
 2024-06-12_20-00-01 2024-06-13_20-00-01 2024-06-14_07-31-41 2024-06-14_07-32-06 2024-06-14_20-00-00 2024-06-15_11-00-00
 2024-06-15_20-00-00 2024-06-15_21-00-00

Skip: 2024-06-09_18-00-00 2024-06-10_16-10-54 2024-06-10_18-00-00 2024-06-11_18-00-00 2024-06-12_04-27-01
 2024-06-12_20-00-01 2024-06-13_20-00-01 2024-06-14_07-31-41 2024-06-14_07-32-06 2024-06-14_20-00-00 2024-06-15_11-00-00
 2024-06-15_20-00-00 2024-06-15_21-00-00
manjaro18.home: Backup of snapshots based on 2024-06-15_21-00-00
java.io.FileNotFoundException: Could not create dir: /tmp/BackupRoot/@BackSnap/manjaro18.home/snapshots
        at de.uhingen.kielkopf.andreas.backsnap.Backsnap.mkDirs(Backsnap.java:309)
        at de.uhingen.kielkopf.andreas.backsnap.Backsnap.backup(Backsnap.java:249)
        at de.uhingen.kielkopf.andreas.backsnap.Backsnap.main(Backsnap.java:167)
sudo umount -v /tmp/BtrfsRoot;sudo rmdir /tmp/BtrfsRoot
sudo umount -v /tmp/BackupRoot;sudo rmdir /tmp/BackupRoot
ende:X ready⏎                                                       
```

I deleted the folder that it was complaining about. @BackSnap/manjaro18/snapshots & @BackSnap/manjaro18.home/snapshots  and it kinda worked another time (just with different errors).

after closing and opening again the same error as above was back again.

Hope you can help, thx.

**Comment by JackDinn** [comment]
Im not sure actually. It does seem to be backing up new snapshots. Its just that when i try to run it to see the gui, it does not show the backup side of the window. Maybe its supposed to be like that? There really is no instructions, im just guessing.

![Screenshot_20240615_220802](https://github.com/andreaskielkopf/BackSnap/assets/5557560/a2183414-44fa-45d3-86f4-05b294a98a50)

**Comment by andreaskielkopf** [comment]
> BackSnap Version 0.6.7.10 (2023/11/02)
> args >  -gi 
You start Backsnap with:
 -g --gui            enable gui (works only with sudo)
 -i --init           init /etc/backsnap.d/local.conf (only with -g)

The -i option is intended to be used only the first time. This creates the necessary configuration files in /etc/backsnap.d/local.conf. For example:

```
ls -lA /etc/backsnap.d
.rw-r--r--@ 485 andreas andreas 2023-10-31 10:31  0_local.conf
.rw-r--r--@ 183 andreas andreas 2023-11-03 12:28  1_server.conf
.rw-r--r--@ 251 andreas andreas 2023-10-31 10:29  2_jitsim2.conf
.rw-r--r--@ 292 andreas andreas 2023-10-31 10:31  3_laptop.conf
.rw-r--r--@ 113 andreas andreas 2023-10-31 10:29  gast.conf
.rw-r--r--@ 132 andreas andreas 2023-10-31 10:31  timeshift.conf
```
My example:
```
# backup local pc per sudo
pc = localhost
# backup local pc per ssh
# pc = root@localhost

# detect and mount backupvolume by scanning for this id (as part of the uuid)
backup_id = 03417033-3745-4ae7-9451-efafcbb9124e

# use these flags for the following backup (optional)
flags = -c -v=5 -a=5 -o=4000 -m=1000
# backuplabel = manjaro18 for snapshots of /
manjaro18 = /

flags = -c -v=5 -a=5 -o=4000 -m=1000
# backuplabel = manjaro18.home for snapshots of /home
manjaro18.home = /home
```

Further calls are then made with, for example:
backsnap -cg
or
backsnap -cga
or
backsnap -c
or
backsnap -h

> Im not sure actually. It does seem to be backing up new snapshots. Its just that when i try to run it to see the gui, it does not show the backup side of the window. Maybe its supposed to be like that? There really is no instructions, im just guessing.

You can test the backup by simply mounting the backup disk under /mnt.
The snapshots should then be visible there. You can view each snapshot to see what's in it and whether it's fully accessible.

👣
