### ISSUE TITLE
Not sure if Backsnap -qi is finding my "source" btrfs partitions correctly

### ISSUE THREAD

**Issue by bmullan** [andreaskielkopf/BackSnap#6]
# System:  
**Ubuntu 24.04 Desktop.** 
**All drives are 2TB SSD**
***I am using Timeshift configured it to Snapshot both System Files and Home.*** 

*On my system I created* **2 subvolumes** *to separate*
 **/@** 
and 
**/@home**

When I execute:
> **sudo backsnap -gi**

and select my destination backup drive ( **/dev/sdd1**) the info displayed seems to indicate it correctly finds source 'root' (ie **/@**) ok.

But if I am reading the output correctly BACKSNAP *fails to see my* **/@home** *subvolume as my 'home' partition*
and _it seems Backsnap assumes 'home' is a traditional "/home" path_ 

**NOTE:**  
*I am creating this Issue in the hopes that there* ***is a config file entry I can use to tell Backsnap that my 'home' is /@home***

---

### My system's FSTAB is:

\# /etc/fstab: static file system information.
\#
\# Use 'blkid' to print the universally unique identifier for a
\# device; this may be used with UUID= as a more robust way to name devices
\# that works even if disks are added and removed. See fstab(5).
\#
\# <file system> <mount point>   <type>  <options>       <dump>  <pass>
\# / was on /dev/nvme1n1p3 during installation
**UUID=85ffb2a1-b12a-4f95-bc44-3aa9525c7588 /               btrfs   defaults,noatime,space_cache=v2,compress=zstd:3,subvol=@** 0       1
\# /boot/efi was on /dev/nvme1n1p1 during installation
UUID=8708-DA09  /boot/efi       vfat    umask=0077      0       1
\# /home was on /dev/nvme1n1p4 during installation
**UUID=5c77b581-a192-4638-b14b-89b6ede56475 /home           btrfs   defaults,noatime,space_cache=v2,compress=zstd:3,subvol=@home** 0       2
\# swap was on /dev/sda3 during installation
UUID=37db3cb0-38c0-4fa8-b4c5-954b8ac70c6d none            swap    sw              0       0
\#
/dev/sdb1 /mnt/lxd-storage-pool auto nosuid,nodev,nofail,x-gvfs-show,x-gvfs-name=lxd-storage-pool,x-gvfs-icon=lxd-storage-pool,x-gvfs-symbolic-icon=lxd-storage-pool 0 0
/dev/sda1 /mnt/incus-storage-pool auto nosuid,nodev,nofail,x-gvfs-show,x-gvfs-name=incus-storage-pool,x-gvfs-icon=incus-storage-pool,x-gvfs-symbolic-icon=incus-storage-pool 0 0
\#
**/dev/sdd /mnt/timeshift-snapshots-backup auto nosuid,nodev,nofail,x-gvfs-show,x-gvfs-name=Timeshift-Snapshots-Backup,x-gvfs-icon=Timeshift-Snapshots-Backup,x-gvfs-symbolic-icon=Timeshift-Snapshots-Backup 0 0
/dev/sdd1 /mnt/Timeshift-Snapshots-Backup auto nosuid,nodev,nofail,x-gvfs-show,x-gvfs-name=Timeshift-Snapshots-Backup,x-gvfs-icon=Timeshift-Snapshots-Backup,x-gvfs-symbolic-icon=Timeshift-Snapshots-Backup 0 0
/dev/sde /mnt/sde auto nosuid,nodev,nofail,noauto,x-gvfs-show,x-gvfs-name=plex-media-server,x-gvfs-icon=plex-media-server,x-gvfs-symbolic-icon=plex-media-server 0 0
/dev/sdd2 /mnt/Timeshift-Snapshots-Bkup auto nosuid,nodev,nofail,x-gvfs-show,x-gvfs-name=Timeshift-Snapshots-Bkup,x-gvfs-icon=Timeshift-Snapshots-Bkup,x-gvfs-symbolic-icon=Timeshift-Snapshots-Bkup 0 0**

---

What follows is a long list of output but I will **highlight** where the failures start and they all appear related to the source "home" directory:

### $ sudo backsnap -qi
BackSnap Version 0.6.8.28 (2024/06/23)
args >  -qi 
java [version=21.0.5, major=21, minor=0, patch=5]
using ThreadPerTaskExecutor
create /etc/backsnap.d/local.conf
Pc[sudo ] & Id:c5e6f54b-9099-4e32-9e74-4839c00b21a7
OneBackup[local.conf, Pc[sudo ]:/ (manjaro18) flags=null]
OneBackup[local.conf, Pc[sudo ]:/home (manjaro18.home) flags=null]

sudo mkdir --mode=000 -p /tmp/BtrfsRoot;sudo mount -t btrfs -o subvol=/,noatime,compress=zstd:9  /dev/nvme0n1p3 /tmp/BtrfsRoot
Backup snapshots from sudo :/

sudo mkdir --mode=000 -p /tmp/BackupRoot;sudo mount -t btrfs -o subvol=/,noatime,compress=zstd:9  /dev/sdd1 /tmp/BackupRoot
Try to use backupDir  sudo :/tmp/BackupRoot
manjaro18: Backup of 2024-11-09_16-05-05
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-09_16-05-05
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-09_16-05-05/@

### At subvol @
9.50GiB 0:00:42 [ 231MiB/s] [          <=>                                     ]free(295),max(3974),total(502)

manjaro18: Backup of 2024-11-10_07-39-37 based on 2024-11-09_16-05-05
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-10_07-39-37
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-10_07-39-37/@
2.32GiB 0:00:09 [ 251MiB/s] [                                 <=>              ]
e:At snapshot @free(349),max(3974),total(500)

manjaro18: Backup of 2024-11-10_11-11-03 based on 2024-11-10_07-39-37
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-10_11-11-03
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-10_11-11-03/@
 431MiB 0:00:05 [82.5MiB/s] [              <=>                                 ]
e:At snapshot @free(350),max(3974),total(500)

manjaro18: Backup of 2024-11-10_15-14-06 based on 2024-11-10_11-11-03
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-10_15-14-06
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-10_15-14-06/@
 194MiB 0:00:03 [58.6MiB/s] [          <=>                                     ]
e:At snapshot @free(350),max(3974),total(500)

manjaro18: Backup of 2024-11-11_07-16-42 based on 2024-11-10_15-14-06
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-11_07-16-42
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-11_07-16-42/@
 291MiB 0:00:02 [ 142MiB/s] [         <=>                                      ]
e:At snapshot @free(350),max(3974),total(500)

manjaro18: Backup of 2024-11-11_14-53-05 based on 2024-11-11_07-16-42
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-11_14-53-05
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-11_14-53-05/@
3.88GiB 0:00:20 [ 192MiB/s] [<=>                                               ]
e:At snapshot @free(350),max(3974),total(500)

manjaro18: Backup of 2024-11-13_07-32-21 based on 2024-11-11_14-53-05
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-13_07-32-21
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-13_07-32-21/@
1.33GiB 0:00:06 [ 207MiB/s] [                   <=>                            ]
e:At snapshot @free(350),max(3974),total(500)

manjaro18: Backup of 2024-11-14_09-13-53 based on 2024-11-13_07-32-21
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-14_09-13-53
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-14_09-13-53/@
3.00GiB 0:00:10 [ 295MiB/s] [                                      <=>         ]
e:At snapshot @free(350),max(3974),total(500)

manjaro18: Backup of 2024-11-14_11-10-04 based on 2024-11-14_09-13-53
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-14_11-10-04
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-14_11-10-04/@
 247MiB 0:00:03 [73.0MiB/s] [    <=>                                           ]
e:At snapshot @free(350),max(3974),total(500)

manjaro18: Backup of 2024-11-15_16-50-08 based on 2024-11-14_11-10-04
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-15_16-50-08
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-15_16-50-08/@
2.03GiB 0:00:05 [ 407MiB/s] [                       <=>                        ]
e:At snapshot @free(350),max(3974),total(500)

manjaro18: Backup of 2024-11-16_20-50-36 based on 2024-11-15_16-50-08
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-16_20-50-36
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-16_20-50-36/@
 491MiB 0:00:03 [ 126MiB/s] [       <=>                                        ]
e:At snapshot @free(350),max(3974),total(500)

manjaro18: Backup of 2024-11-17_19-09-04 based on 2024-11-16_20-50-36
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-17_19-09-04
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-17_19-09-04/@
 485MiB 0:00:02 [ 167MiB/s] [         <=>                                      ]
e:At snapshot @free(350),max(3974),total(500)

manjaro18: Backup of 2024-11-18_11-00-01 based on 2024-11-17_19-09-04
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-18_11-00-01
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-18_11-00-01/@
1.08GiB 0:00:03 [ 320MiB/s] [            <=>                                   ]
e:At snapshot @free(350),max(3974),total(500)

manjaro18: Backup of 2024-11-18_11-02-34 based on 2024-11-18_11-00-01
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-18_11-02-34
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-18_11-02-34/@
 746KiB 0:00:02 [ 315KiB/s] [  <=>                                             ]
e:At snapshot @free(350),max(3974),total(500)

manjaro18: Backup of 2024-11-18_13-12-47 based on 2024-11-18_11-02-34
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-18_13-12-47
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-18_13-12-47/@
1.21GiB 0:00:03 [ 314MiB/s] [                  <=>                             ]
e:At snapshot @free(350),max(3974),total(500)

manjaro18: Backup of 2024-11-18_15-52-51 based on 2024-11-18_13-12-47
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-18_15-52-51
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-18_15-52-51/@
 175MiB 0:00:02 [62.9MiB/s] [    <=>                                           ]
e:At snapshot @free(350),max(3974),total(500)

manjaro18: Backup of 2024-11-18_15-54-42 based on 2024-11-18_15-52-51
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-18_15-54-42
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-18_15-54-42/@
 365MiB 0:00:01 [ 268MiB/s] [      <=>                                         ]
e:At snapshot @free(350),max(3974),total(500)

manjaro18: Backup of 2024-11-18_15-57-11 based on 2024-11-18_15-54-42
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-18_15-57-11
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-18_15-57-11/@
62.6MiB 0:00:01 [56.3MiB/s] [  <=>                                             ]
e:At snapshot @free(350),max(3974),total(500)

manjaro18: Backup of 2024-11-18_16-54-27 based on 2024-11-18_15-57-11
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18/2024-11-18_16-54-27
At subvol /tmp/BtrfsRoot/timeshift-btrfs/snapshots/2024-11-18_16-54-27/@
 246MiB 0:00:00 [ 339MiB/s] [   <=>                                            ]
e:At snapshot @free(350),max(3974),total(500)

java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:296)
	at java.base/java.nio.file.Path.resolve(Path.java:516)
	at de.uhingen.kielkopf.andreas.backsnap.Backsnap.backup(Backsnap.java:256)
	at de.uhingen.kielkopf.andreas.backsnap.Backsnap.main(Backsnap.java:183)

### Backup snapshots from sudo :**/home**
Try to use backupDir  sudo :/tmp/BackupRoot
manjaro18.home: Backup of 2024-11-09_16-05-05 based on 2024-11-18_16-54-27
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-09_16-05-05
ERROR: unable to resolve /home/../timeshift-btrfs/snapshots/2024-11-09_16-05-05/@home
ERROR: empty stream is not considered validfree(334),max(3974),total(500)

manjaro18.home: Backup of 2024-11-10_07-39-37 based on 2024-11-09_16-05-05
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-10_07-39-37
ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-09_16-05-05/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)

manjaro18.home: Backup of 2024-11-10_11-11-03 based on 2024-11-10_07-39-37
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-10_11-11-03
_**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-10_07-39-37/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**_

manjaro18.home: Backup of 2024-11-10_15-14-06 based on 2024-11-10_11-11-03
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-10_15-14-06
**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-10_11-11-03/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**

manjaro18.home: Backup of 2024-11-11_07-16-42 based on 2024-11-10_15-14-06
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-11_07-16-42
**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-10_15-14-06/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**

manjaro18.home: Backup of 2024-11-11_14-53-05 based on 2024-11-11_07-16-42
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-11_14-53-05
**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-11_07-16-42/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**

manjaro18.home: Backup of 2024-11-13_07-32-21 based on 2024-11-11_14-53-05
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-13_07-32-21
**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-11_14-53-05/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**

manjaro18.home: Backup of 2024-11-14_09-13-53 based on 2024-11-13_07-32-21
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-14_09-13-53
**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-13_07-32-21/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**

manjaro18.home: Backup of 2024-11-14_11-10-04 based on 2024-11-14_09-13-53
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-14_11-10-04
**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-14_09-13-53/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**

manjaro18.home: Backup of 2024-11-15_16-50-08 based on 2024-11-14_11-10-04
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-15_16-50-08
**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-14_11-10-04/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**

manjaro18.home: Backup of 2024-11-16_20-50-36 based on 2024-11-15_16-50-08
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-16_20-50-36
**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-15_16-50-08/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**

manjaro18.home: Backup of 2024-11-17_19-09-04 based on 2024-11-16_20-50-36
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-17_19-09-04
**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-16_20-50-36/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**

manjaro18.home: Backup of 2024-11-18_11-00-01 based on 2024-11-17_19-09-04
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-18_11-00-01
**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-17_19-09-04/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**

manjaro18.home: Backup of 2024-11-18_11-02-34 based on 2024-11-18_11-00-01
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-18_11-02-34
**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-18_11-00-01/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**

manjaro18.home: Backup of 2024-11-18_13-12-47 based on 2024-11-18_11-02-34
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-18_13-12-47
**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-18_11-02-34/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**

manjaro18.home: Backup of 2024-11-18_15-52-51 based on 2024-11-18_13-12-47
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-18_15-52-51
**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-18_13-12-47/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**

manjaro18.home: Backup of 2024-11-18_15-54-42 based on 2024-11-18_15-52-51
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-18_15-54-42
**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-18_15-52-51/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**

manjaro18.home: Backup of 2024-11-18_15-57-11 based on 2024-11-18_15-54-42
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-18_15-57-11
**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-18_15-54-42/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**

manjaro18.home: Backup of 2024-11-18_16-54-27 based on 2024-11-18_15-57-11
sudo mkdir -pv /tmp/BackupRoot/@BackSnap/manjaro18.home/2024-11-18_16-54-27
**ERROR: realpath /home/../timeshift-btrfs/snapshots/2024-11-18_15-57-11/@home failed: No such file or directory
ERROR: empty stream is not considered validfree(342),max(3974),total(500)**

---

sudo umount -v /tmp/BtrfsRoot;sudo rmdir /tmp/BtrfsRoot
sudo umount -v /tmp/BackupRoot;sudo rmdir /tmp/BackupRoot
ende:X ready to exit java
254 ==>
BackSnap is made for making backups of btrfs snapshots on linux

Anything I can do to make Backsnap work?
thanks

**Comment by andreaskielkopf** [comment]
Your fstab shows that your @home subvolume lies not on the same btrfs-volume as your @ subvolume. This sort of partitioning is not supported by backsnap.

Backsnap requires that all btrfs subvolumes to be backed up on a computer originate from the **same btrfs volume**.

* Your /@(/) is located on volume UUID=85ffb2a1-b12a-4f95-bc44-3aa9525c7588
and
* your @home(/home) is located on volume UUID=5c77b581-a192-4638-b14b-89b6ede56475

Backsnap mounts only **one** btrfs volume containing the snapshots and **one** btrfs volume containing the backups.

> Anything I can do to make Backsnap work?
thanks

The only thing that comes to mind at the moment is that you try to use a btrfs layout that is more in line with the standard. 🤷‍♂
